### ISSUE TITLE
말 추가

### ISSUE THREAD

**Issue by aspective04** [upnl/finger-yutnori#10]
## 개발 목표
윷놀이 말을 추가한다.

## 구현 방법
Token 오브젝트를 생성하고 적당한 이미지를 추가한다.

**Comment by nick11967** [comment]
Token은 Prefab으로 만드는 것이 좋겠네요!
Token이 어느 방향으로든 움직이는 스크립트도 같이 넣어보면 좋을 것 같습니다.

**Comment by nick11967** [comment]
유니티에서 DoMove와 같은 함수를 사용하면 부드러운 애니메이션이 가능해요. 한 번 찾아보고 구현해보세요.
