### ISSUE TITLE
로그인 창 구현

### ISSUE THREAD

**Issue by cute-gorilla** [upnl/finger-yutnori#11]
## 개발 목표
시작 전 플레이어의 이름과 손 선택을 받고 다음 씬으로 넘어가도록 구현합니다.
데이터는 어떻게 넘길지 고민중..

## 구현 방법
gamestatemanager를 사용해 데이터를 받고 확인 버튼을 누르면 다음씬으로 넘어갑니다.

데이터를 넘기는 방법은 playerprefs랑 dontdestroyonload랑 있던데 어떤거로 해야할지 모르겠음..

**Comment by nick11967** [comment]
저는 다른 프로젝트에서 dontdestroyonload 사용해요. 참고하세요.

**Comment by nick11967** [comment]
보니까 playerprefs는 데이터만 넣었다 빼는 방식이고 dontdestroyonload는 오브젝트 자체를 넘기는 방식인 것 같네요. 이름, 손 선택창에서는 그 두 가지 정보만 받지만 대결 씬에서는 플레이어에 여러 정보들이 필요할 거 같아요. (아마도?) playerprefs를 써보는 게 어떨까 싶습니다. 뭐 맘에 드는 걸로 해도 상관 없고요.

**Comment by cute-gorilla** [comment]
> 보니까 playerprefs는 데이터만 넣었다 빼는 방식이고 dontdestroyonload는 오브젝트 자체를 넘기는 방식인 것 같네요. 이름, 손 선택창에서는 그 두 가지 정보만 받지만 대결 씬에서는 플레이어에 여러 정보들이 필요할 거 같아요. (아마도?) playerprefs를 써보는 게 어떨까 싶습니다. 뭐 맘에 드는 걸로 해도 상관 없고요.

playerprefs 써서 플레이어 이름이랑 무슨 손 선택했는지 넘기기로 함..
그리고 생각해보니깐 너가 저번에 말했던 것 처럼 윷놀이 위에 가위바위보 띄우는 식으로 한 씬에서 하는게 나을 듯???
2개로 하면 데이터 옮기는게 너무 많을 것 같아서;;

**Comment by nick11967** [comment]
아직 구현이 안 된 것 같은데 왜 close 하셨나요?
이유를 공유해주시면 좋을 것 같네요.

**Comment by cute-gorilla** [comment]
> 아직 구현이 안 된 것 같은데 왜 close 하셨나요? 이유를 공유해주시면 좋을 것 같네요.

아 이거 어제 다시 쓰려고 축구보면서 다시쓰다가 안올리고 자버렸다 곧 다시 올릴게요
