### ISSUE TITLE
그림 만들기

### ISSUE THREAD

**Issue by ysm5864** [upnl/finger-yutnori#12]
## 개발 목표

게임에서 사용할 손가락 그림과 캐릭터를 만들고자함 : 도트찍기
1. 캐릭터 
- [x] 남자&여자 캐릭터
- [x] 달리는 모습 6컷으로 구성
- [ ] 손가락 battle 중 이겼을 때 / 졌을 때 모션
- [ ] 말 업기 모션
- [ ] 말 잡기 모션

2. 손가락
- [x] 손가락 선택 과정에서 선택 / 비선택 모션 (검정 테두리 / 빨강 테두리)
- [x] 손가락 사이 관계도

- [ ] 3. 게임 버튼
- 완료버튼
- 확인버튼
- 다음버튼
- 메인화면 게임 시작 버튼

- [ ] 4. 기타
- 화살표 (왼쪽 / 왼쪽 아래 대각선 / 오른쪽 / 오른쪽 아래 대각선 / 아래)
- 게임 로고 

## 구현 방법
참고자료 : 
https://www.youtube.com/watch?v=b3J2SInvuwM

**Comment by nick11967** [comment]
좋아요! 작업 중간중간 디코에 한 번씩 보여주면 좋을 것 같아요.

**Comment by nick11967** [comment]
굿 아주 잘 하고 있어요
