### ISSUE TITLE
Battle 씬 UI 제작

### ISSUE THREAD

**Issue by jpyoon0519** [upnl/finger-yutnori#16]
## 개발 목표
Battle Scene의 UI를 제작하는 것이 목표입니다.

## 구현 방법
Canvas 안에 Battle scene에 필요한 오브젝트들을 미리 모두 만들어둡니다.

**Comment by nick11967** [comment]
좋아요 첫 issue를 잘 만들어 주었어요.
다음부터는 구현 방법에 조금 더 자세한 내용을 적어주면 좋을 것 같아요.
필요한 오브젝트가 무엇인지, 그걸 뭘로 만들 생각인지 등등을 말이죠.
이렇게 이슈를 적는 것은 무엇을 할 예정인지 팀원들과 공유하기 위함이 첫 번째 이유이고,
제가 목표나 방법을 보고 힌트 또는 도움이 될 수 있는 정보를 제공하기 위함이 두 번째에요. 참고하세요~
추가로 issue를 만들 때 오른쪽에 Assignees에 자신을 추가해주면 좋아요
