### ISSUE TITLE
로그인 창 구현

### ISSUE THREAD

**Issue by cute-gorilla** [upnl/finger-yutnori#18]
## 개발 목표
로그인 창을 구현합니다.

## 구현 방법
playerprefs를 이용하여 선택한 손, 플레이어의 이름을 전달할 예정입니다.
사용자의 이름과 선택만 넘겨주면 되기 때문에
로그인 씬과 다른 씬을 굳이 연결할 필요가 없는 것 같아,
이 씬에서만 사용하는 LoginManager 스크립트를 사용할 예정입니다.

**Comment by cute-gorilla** [comment]
나머지는 다 했는데 해결되지 않은게
한 씬에서 해결하면
-인풋필드랑 토글그룹을 2개 만들어서 액티브 하는 방식으로 2명의 입력을 받을지(이건 좀 아닌거 같긴 함.)
-그래서 씬을 재활용 할 수 있나?? 방법을 찾는중
아니면 그냥 씬 2개를 이용할지 고민중입니다

**Comment by nick11967** [comment]
씬을 재활용 하는 방법으로 화면 크기와 같은 UI를 만드는 방법이 있을 것 같아요. 추가로 캔버스를 만든다고 생각할 수도 있을 것 같네요. 이 캔버스 아래에 입력 피드 등을 둔 다음에 캔버스 자체를 화면 밖으로 뺐다가 들이는 방식을 생각할 수 있을 것 같아요.

**Comment by nick11967** [comment]
하지만 로그인 씬은 따로 두는 게 맞을 것 같아요. 기능면에서 다른 것들과 분리되기 때문에 씬을 분리시키는 것이 좋겠습니다.

**Comment by nick11967** [comment]
음 제가 잘못 이해한 것 같네요. 한 화면에서 두 명의 정보를 받기가 어려울 것 같다는 의미인가요?

**Comment by nick11967** [comment]
한 화면에 두 개를 만들어도 될 것 같아요. 목록을 보여주듯 줄 두 개를 만들어서 입력을 받으면 충분할 것 같습니다.

**Comment by cute-gorilla** [comment]
> 음 제가 잘못 이해한 것 같네요. 한 화면에서 두 명의 정보를 받기가 어려울 것 같다는 의미인가요?

맞습니다. 토글그룹이랑 인풋필드를 2개씩 만들어서(아니면 캔버스를 2개 만들어서) 버튼을 누를떄 setactive를 이용하면 쉽게 구현은 가능한데 어떻게 할지 고민중..

**Comment by nick11967** [comment]
제가 충분히 자세하기 말은 안 해둬서 고민한 것 같네요. 앞으로 화면 구성도 기획에 그려둘 수 있도록 하겠습니다.

**Comment by cute-gorilla** [comment]
> 제가 충분히 자세하기 말은 안 해둬서 고민한 것 같네요. 앞으로 화면 구성도 기획에 그려둘 수 있도록 하겠습니다.

그러면 한 화면에 두 플레이어의 입력을 모두 받게 할까요?

**Comment by nick11967** [comment]
> > 제가 충분히 자세하기 말은 안 해둬서 고민한 것 같네요. 앞으로 화면 구성도 기획에 그려둘 수 있도록 하겠습니다.
> 
> 
> 
> 그러면 한 화면에 두 플레이어의 입력을 모두 받게 해서 한번에 할까요??

네 그렇게 하면 됩니다.
