### ISSUE TITLE
말 행동 구현

### ISSUE THREAD

**Issue by aspective04** [upnl/finger-yutnori#29]
## 개발 목표
윷놀이 말의 움직임, 상호작용 등을 구현합니다.

## 구현 방법
totalDist라는 변수로 말이 가야 할 칸의 수를 나타내고, movedDist로 말이 이번 턴에 간 칸의 수를 나타냅니다.
움직임 구현 예시)
movedDist가 totalDist와 같다면 턴을 종료합니다.
1. 말이 upperPoints 중 하나에 위치해 있다면
(1) 마지막 인덱스에 위치한다면 upperLeftPoint로 이동하고, movedDist를 1 증가시킵니다.
(2) 그렇지 않다면 upperPoints의 다음 인덱스로 이동하고, movedDist를 1 증가시킵니다.

2. 말이 upperLeftPoint에 위치해 있다면
(1) movedDist가 0이면 leftDiagPoints의 첫 인덱스로 이동하고, movedDist를 1 증가시킵니다.
(2) 그렇지 않다면 leftPoints의 첫 인덱스로 이동하고, movedDist를 1 증가시킵니다.

**Comment by nick11967** [comment]
1.은 변에 위치할 때의 움직임, 2.은 꼭짓점에 위치할 때의 움직임인 것이네요.
코드 올려주시면 자세히 확인하도록 하겠습니다.
