### ISSUE TITLE
스켈레톤 파일 구현

### ISSUE THREAD

**Issue by cute-gorilla** [upnl/finger-yutnori#3]
## 개발 목표
간단하게 스켈레톤 파일을 제작합니다.

## 구현 방법
화면 비율은 모바일 비율인 9:16입니다.
씬은 우선 간략하게 3가지 씬으로 나누었습니다.
1.  게임 시작 전 로그인 페이지
2.  두 플레이어가 대결을 하는 페이지
3. 윷놀이를 하는 페이지

**Comment by nick11967** [comment]
세 개의 씬을 만들려고 하는 건가요? 좋습니다.

**Comment by cute-gorilla** [comment]
> 세 개의 씬을 만들려고 하는 건가요? 좋습니다.

내가 하는 손가락 가위바위보 부분은 기본적인 것만 구현하면 한 씬 안에서 처리하는게 깔끔할 것 같아서 일단 이렇게 해놨는데, 온라인 버전이랑 추가 기능 생각해보면 어떻게 할지 고민좀 해봐야할듯..

**Comment by nick11967** [comment]
한 가지 추천하는 방법은 화면 크기와 같은 네모난 상자를 윷놀이 씬에 만들어서 필요할 때만 보이게 만드는 것입니다. 물론 이럴 때  가위바위보를 하는 동안은 윷판에 관련된 어떤 것도 눌리지 않도록 하는 것이 중요하겠죠.
