### ISSUE TITLE
윷놀이 플레이어 구현

### ISSUE THREAD

**Issue by aspective04** [upnl/finger-yutnori#34]
## 개발 목표
윷놀이를 플레이할 플레이어를 구현합니다.

## 구현 방법
Player 오브젝트를 만들고 각 Player가 Token을 생성하고 움직일 수 있도록 할 생각입니다.

**Comment by nick11967** [comment]
오늘 낮에 작업할 때 Player가 Token을 갖는 게 아니라 TokenManager에서 생성한 Token을 관리하는 것으로 확인했습니다. 게속해서 진행하시고 풀리퀘스트 올려주시면 됩니다.
