### ISSUE TITLE
개발 목표 1 - 그림 2,4 구현

### ISSUE THREAD

**Issue by junyeong04** [upnl/finger-yutnori#38]
## 개발 목표
손가락을 선택한 플레이어가 첫번째라면 그림2가, 두번째라면 그림4가 나오도록 구현

## 구현 방법
UIManager의 OnClickDoneButton에 player라는 변수를 만들어 플레이어를 구분한다.
플레이어에 따라 그림2와 그림4가 나오도록 버튼 및 텍스트 등을 이동시킨다.

**Comment by nick11967** [comment]
변수 이름은 curPlayer로 하면 좋을 것 같습니다.
