### ISSUE TITLE
PlayerClass 생성

### ISSUE THREAD

**Issue by cute-gorilla** [upnl/finger-yutnori#42]
## 개발 목표

- [x] 플레이어의 손 선택, 이름과 battle씬에서 선택한 손가락을 변수로 갖는 PlayerClass를 개발합니다.
- [x] GameManager가 start할 때 playerprefs를 이용해 PlayerClass instance 2개를 생성하도록 합니다.

## 구현 방법
PlayerClass 스크립트를 작성합니다.
이후, battle씬에서 각 플레이어가 손가락 선택하는 작업을 하면 PlayerClass에 그 값을 저장한 뒤, BattleManager라는 가위바위보 규칙을 관리하는 매니저를  만들어 누가 승리하였는지 판별하도록 하면 좋을 것 같습니다.

**Comment by nick11967** [comment]
좋습니다
