### ISSUE TITLE
TokenManager 스크립트 수정

### ISSUE THREAD

**Issue by aspective04** [upnl/finger-yutnori#44]
## 개발 목표
TokenManager.cs 스크립트를 수정합니다.

## 구현 방법
PR (#43)에서 주어진 피드백을 바탕으로 스크립트에서 개선할 부분을 찾고 수정하겠습니다.

**Comment by nick11967** [comment]
github는 신기하게 #을 괄호()와 함께 쓰면 자동으로 해당 PR이나 이슈로 링크를 걸어주더라고요. 그래서 구현 방법에 괄호를 추가했습니다.

**Comment by nick11967** [comment]
디코에서도 말했듯이 뒷도로 시작지점에 돌아간 경우 도 이상이 나오면 나는 거고, 뒷도가 나오면 시작하지 않은 상태로 돌아가면 됩니다.

**Comment by nick11967** [comment]
개선할 부분이 어떤 것인지 먼저 간단한 글로 알려주면 좋을 것 같습니다!
