### ISSUE TITLE
가위바위보 승패 구현

### ISSUE THREAD

**Issue by jpyoon0519** [upnl/finger-yutnori#45]
## 개발 목표
Battle Scene에서 가위바위보 승패를 띄우는 화면을 구현하려 합니다.

## 구현 방법
지금까지 Battle Scene에서는 각 플레이어의 선택을 저장하는 변수와, 다른 플레이어의 선택을 기다리는 장면이 구현됐습니다. 이 두 기능과 승패결과 확인 화면은 다소 유사한 면이 있다고 생각해서, 기존의 코드들을 검토해 유사한 방향으로 새로 화면을 제작하려 합니다.

**Comment by nick11967** [comment]
그러면 승패를 판정하는 코드까지 구현할 생각인가요?

**Comment by jpyoon0519** [comment]
풀 리퀘 올린 다음에 봤습니다;; 죄송합니다 일단 캔버스 2개 더 추가해서 ui까지 만들었습니다 uimanager 스크립트를 크게 확장했는데 다른 manager 스크립트 쓸까 하다가 오히려 너무 번잡해질 거 같아서 기존 코드를 확장하는 식으로 작업했습니다

**Comment by nick11967** [comment]
> 풀 리퀘 올린 다음에 봤습니다;; 죄송합니다 일단 캔버스 2개 더 추가해서 ui까지 만들었습니다 uimanager 스크립트를 크게 확장했는데 다른 manager 스크립트 쓸까 하다가 오히려 너무 번잡해질 거 같아서 기존 코드를 확장하는 식으로 작업했습니다

좋아요 읽어보니 UIManager에서 필요한 부분이었던 것 같아요. 승패 판정하는 함수는 나중에 GameManager나 다른 곳을 빼는 것이 좋긴 하겠네요. 이건 나중에 해도 괜찮을 것 같고 지금 구성은 좋습니다!
