### ISSUE TITLE
soundmanager 만들기

### ISSUE THREAD

**Issue by cute-gorilla** [upnl/finger-yutnori#61]
## 개발 목표
soundmanager를 만들고 넣을 음원을 찾습니다.

## 구현 방법
soundmanager를 세미나떄와 비슷하게 만들고 들어갈 음원을 열심히 고민합니다

**Comment by nick11967** [comment]
배경음도 찾아주면 너무 좋고요. 효과음 위주로 찾아줘도 좋을 것 같습니다.
내일 윷가락 던지는 소리 녹음할까요?
