### ISSUE TITLE
말 업기, 잡기 구현

### ISSUE THREAD

**Issue by aspective04** [upnl/finger-yutnori#64]
## 개발 목표
말을 업는 기능과 잡는 기능을 구현합니다.

## 구현 방법
TokenGroup 오브젝트를 만들어, TokenManager와 각 Token으로부터 정보를 얻어 가능한 모든 경로 표시, 동시 이동 등의 기능을 구현합니다.

**Comment by nick11967** [comment]
좋습니다~

**Comment by nick11967** [comment]
`TokenGroup`을 완성하면 `PrepareManager`에서도 `TokenGroup`을 사용하도록 수정해야 할 겁니다. 그래서 우선은 개발을 진행하다가 내일 최대한 빠르게 `PrepareManager`를 main에 머지하고 그걸 pull로 받아와서 수정하는 작업을 같이하면 될 것 같습니다. 어차피 내일 만나니까 수정해야 하는 부분은 내일 더 얘기해봅시다.
