### ISSUE TITLE
말 이동 시 걸어가는 이미지 변경

### ISSUE THREAD

**Issue by ysm5864** [upnl/finger-yutnori#68]
## 개발 목표
말이 한 칸 이동할 때 몇 초 걸릴지 정하고, 
해당 시간 만큼 프레임 7개를 한바퀴 돌리면서 이미지 변경하기

2칸을 움직인다고 하면 두 바퀴 돌리면서 이미지 변경하기

## 구현 방법
img 변경 코드 이용

**Comment by nick11967** [comment]
어떤 걸 하는 건지 정확히 알기 어려운데 조금 더 자세히 설명해줄 수 있을까요?

**Comment by ysm5864** [comment]
구현 방법은 찾아보고 있는데, 정하게 되면 수정할게요!

**Comment by nick11967** [comment]
개발 목표에 '칸 수에 따라' 이미지를 바꾼다고 했는데 이건 어떤 걸 말하는 건가요?

**Comment by ysm5864** [comment]
한 칸 이동할때 프레임 7개를 한바퀴 변경하는 식으로 할 건데, 
두 칸 가면 두바퀴 돌린다 이런식으로 코드를 구성할 겁니다

**Comment by nick11967** [comment]
아 네 이해했습니다! 좋아요
