### ISSUE TITLE
Login 씬에서 손 미선택 시 랜덤 선택됨을 텍스트로 보이고 기능 구현

### ISSUE THREAD

**Issue by junyeong04** [upnl/finger-yutnori#79]
먼저 텍스트는 영어로 작성

`ToggleGroup.cs`의 함수를 이용하여 선택 여부 확인

랜덤 선택 기능 구현 방법은 고민 중

**Comment by nick11967** [comment]
윷놀이 씬에서 디코로 보낸 상자 이미지도 위아래로 넣어주세요
